### ISSUE TITLE
how to install this module

### ISSUE THREAD

**Issue by brithbutter** [dvarrazzo/py-ltree#5]
I know this may be a stupid question... but I can't install this module with pipy. Moreover, there is no any instruction of installation in README. Could anyone provide an instruction?

**Comment by dvarrazzo** [comment]
I tried uploading on PyPI but at the time failed. It might have been a temporary failure in the PyPI server but hadn't retried since.

In order to install it, it should be enough check out and run `python setup.py install` in the check out dir. Or read the pip docs about [installing from vcs](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)
